// {{ module_name }} BFM — Auto-generated by digital-verify-pro
// Protocol-agnostic signal-level Bus Functional Model

interface {{ module_name }}_bfm ({{ protocol.name }}_if vif);
{% for sig in protocol.signals %}
{%- if sig.direction == "output" or sig.direction == "bidir" %}
  // Drive {{ sig.name }}
  task drive_{{ sig.name }}(logic [{{ sig.width|default(1) - 1 }}:0] value);
    @(posedge vif.{{ clk_name }});
    vif.{{ sig.name }} <= value;
  endtask
{%- endif %}
{%- endfor %}
{% for sig in protocol.signals %}
{%- if sig.direction != "output" %}
  // Read {{ sig.name }}
  task read_{{ sig.name }}(output logic [{{ sig.width|default(1) - 1 }}:0] value);
    value = vif.{{ sig.name }};
  endtask
{%- endif %}
{%- endfor %}
{% for sig in protocol.signals %}
{%- if sig.direction != "output" %}
  // Wait for {{ sig.name }}
  task wait_for_{{ sig.name }}(logic [{{ sig.width|default(1) - 1 }}:0] target, int timeout_ns = 10000);
    fork
      begin
        #(timeout_ns);
        `uvm_warning("BFM_TIMEOUT", $sformatf("Wait for {{ sig.name }}==%0h timed out", target))
      end
      begin
        wait(vif.{{ sig.name }} === target);
      end
    join_any
    disable fork;
  endtask
{%- endif %}
{%- endfor %}

  // Wait N clock cycles
  task wait_cycles(int n = 1);
    repeat(n) @(posedge vif.{{ clk_name }});
  endtask

  // Wait for reset release
  task wait_for_reset();
    @(negedge vif.{{ rst_name }});
    @(posedge vif.{{ rst_name }});
  endtask
endinterface
