// {{ module_name }} Scoreboard — Auto-generated by digital-verify-pro
// Generic scoreboard with APB transaction tracking

class {{ module_name }}_sb extends uvm_scoreboard;
  `uvm_component_utils({{ module_name }}_sb)

  uvm_analysis_imp {{ module_name }}_sb) apb_export;
  int apb_writes, apb_reads, errors;

  function new(string n, uvm_component p); super.new(n, p); endfunction

  function void build_phase(uvm_phase phase);
    super.build_phase(phase);
    apb_export = new("apb_export", this);
  endfunction

  function void write_apb(apb_txn txn);
    if (txn.write) begin
      apb_writes++;
      `uvm_info("SB", $sformatf("APB write: addr=0x%0h data=0x%0h", txn.addr, txn.data), UVM_MEDIUM)
    end else begin
      apb_reads++;
      `uvm_info("SB", $sformatf("APB read:  addr=0x%0h data=0x%0h", txn.addr, txn.data), UVM_MEDIUM)
    end
  endfunction

  function void report_phase(uvm_phase phase);
    string s = (errors == 0) ? "PASS" : "FAIL";
    `uvm_info("SB_REPORT", $sformatf(
      "\n===== Scoreboard (%s) ====="
      "\n  APB writes=%0d reads=%0d errors=%0d"
      "\n  Registers: {{ num_registers }}  Fields: {{ num_fields }}"
      "\n===========================",
      s, apb_writes, apb_reads, errors), UVM_MEDIUM)
  endfunction
endclass : {{ module_name }}_sb
