"""
template_engine.py — Jinja2-based generic SV template renderer.

Rewritten to be protocol-agnostic: templates iterate over spec data
(interfaces, signals, registers, fields) rather than being hardcoded
for specific protocols (GPIO, I2C, etc.).

Template variables use {{ var }} / {% for %} / {% if %} syntax (Jinja2).
"""

import os, sys, json, datetime
from typing import Dict, List, Optional, Any, Tuple
from jinja2 import Environment, FileSystemLoader, StrictUndefined

TEMPLATES_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "templates")

# Jinja2 environment with cache disabled for development
_jinja_env = Environment(
    loader=FileSystemLoader(TEMPLATES_DIR),
    undefined=StrictUndefined,
    trim_blocks=True,
    lstrip_blocks=True,
    autoescape=False,
)

# ── Filter: indent multi-line text ──
def _indent(text: Optional[str], width: int = 2) -> str:
    """Indent multi-line text by width spaces."""
    if not text:
        return ""
    lines = text.split("\n")
    return "\n".join(" " * width + l if l.strip() else "" for l in lines)


_jinja_env.filters["indent"] = _indent


def load_template(name: str) -> Optional[str]:
    """Load a template by name.  If name has an extension, use as-is;
    otherwise append .sv.tpl suffix. Returns None if not found."""
    base, ext = os.path.splitext(name)
    if ext:
        path = os.path.join(TEMPLATES_DIR, name)
    else:
        path = os.path.join(TEMPLATES_DIR, name + ".sv.tpl")
    if os.path.exists(path):
        with open(path, "r", encoding="utf-8") as f:
            return f.read()
    return None


def render(template_name: str, data: Dict[str, Any]) -> Optional[str]:
    """Load and render a template with data dict using Jinja2. Returns None if template not found."""
    tpl = load_template(template_name)
    if tpl is None:
        return None
    try:
        template = _jinja_env.from_string(tpl)
        return template.render(**data)
    except Exception as e:
        print(f"  [TEMPLATE ERROR] {template_name}: {e}")
        print(f"  [FIX] Check template syntax in pipeline/templates/{template_name}")
        raise  # Re-raise so caller can detect failure


def render_to_file(template_name, data, out_path):
    """Render a template and write the result. Returns True on success."""
    try:
        content = render(template_name, data)
    except Exception:
        print(f"  [FAIL] Could not generate {os.path.basename(out_path)} — template error")
        return False
    if content is None:
        print(f"  [WARN] Template not found: {template_name}")
        return False
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by digital-verify-pro template engine\n")
        f.write(content)
    return True


# ═══════════════════════════════════════════════════════════════
# Spec data normalization — shared by all pipeline stages
# ═══════════════════════════════════════════════════════════════

def build_spec_data(spec_path: str) -> Dict[str, Any]:
    """Load spec YAML and build a normalized data dict for templates."""
    import yaml
    with open(spec_path, "r", encoding="utf-8-sig") as f:
        spec = yaml.safe_load(f)

    module = spec.get("module", {})
    data = {
        "module_name": module.get("name", "unknown"),
        "module_desc": module.get("description", ""),
        "module_version": module.get("version", "1.0"),
        "date": datetime.datetime.now().strftime("%Y-%m-%d"),
        "clocks": spec.get("clocks", []),
        "resets": spec.get("resets", []),
        "interfaces": spec.get("interfaces", []),
        "registers": spec.get("registers", []),
        "test_scenarios": spec.get("verification", {}).get("test_scenarios", []),
        "coverage_goals": spec.get("verification", {}).get("coverage_goals", {}),
        "fsm": spec.get("fsm", None),
    }

    # ── Clock & Reset helpers ──
    data["clk_name"] = data["clocks"][0]["name"] if data["clocks"] else "clk"
    rst = data["resets"][0] if data["resets"] else {}
    data["rst_name"] = rst.get("name", "rstn")
    data["rst_polarity"] = rst.get("polarity", "active_low")
    data["rst_polarity_expr"] = "!" if data["rst_polarity"] == "active_low" else ""

    # ── Interface helpers ──
    for iface in data["interfaces"]:
        sigs = iface.get("signals", [])
        iface["signal_names"] = [s["name"] for s in sigs]
        # Build signal declarations with correct width/direction
        decl_lines = []
        for s in sigs:
            width_str = f"[{int(s['width'])-1}:0] " if int(s.get("width", 1)) > 1 else ""
            if s.get("direction") == "bidir":
                decl_lines.append(f"  wire {width_str}{s['name']};")
            elif s.get("direction") == "input":
                decl_lines.append(f"  logic {width_str}{s['name']};  // input")
            elif s.get("direction") == "output":
                decl_lines.append(f"  logic {width_str}{s['name']};  // output")
            else:
                decl_lines.append(f"  logic {width_str}{s['name']};")
        iface["signal_decls"] = "\n".join(decl_lines)

    # ── Identify APB, protocol, interrupt interfaces ──
    data["apb"] = next((i for i in data["interfaces"] if i["type"] == "APB"), {})
    data["protocol"] = next((i for i in data["interfaces"]
                             if i["type"] not in ("APB", "interrupt")), {})
    data["interrupt"] = next((i for i in data["interfaces"] if i["type"] == "interrupt"), {})

    # ── Register helpers ──
    reg_constants = []
    reg_list = []
    reg_addr_map = {}
    for i, r in enumerate(data["registers"]):
        offset_raw = r.get("offset", "0x000")
        try:
            offset = int(offset_raw, 16) if isinstance(offset_raw, str) else i
        except (ValueError, TypeError):
            offset = i
        name = r.get("name", f"REG{i}")
        offset_hex = f"0x{offset:04X}"
        reg_constants.append(f"  localparam ADDR_{name.upper()} = 32'h{offset:04X};")
        reg_list.append({"name": name, "offset": offset_hex, "fields": r.get("fields", [])})
        reg_addr_map[name] = offset_hex
    data["reg_constants"] = "\n".join(reg_constants)
    data["reg_list"] = reg_list
    data["reg_addr_map"] = reg_addr_map

    # ── Register fields detail (flat list) ──
    reg_fields_detail = []
    for r in data["registers"]:
        for f in r.get("fields", []):
            raw_access = f.get("access", "rw")
            # Derive hwaccess from access if not explicitly set
            raw_hwaccess = f.get("hwaccess", None)
            if raw_hwaccess is None:
                if raw_access == "rw":
                    raw_hwaccess = "hrw"
                elif raw_access == "ro":
                    raw_hwaccess = "hro"
                elif raw_access == "wo":
                    raw_hwaccess = "hwo"
                elif raw_access == "w1c":
                    raw_hwaccess = "hro"
                else:
                    raw_hwaccess = "hrw"
            # Derive swacc (SW-side abstraction)
            swacc_map = {
                "rw": "RW", "ro": "RO", "wo": "WO",
                "w1c": "W1C", "w1s": "W1S", "w1t": "W1T",
                "rw1c": "RW1C", "rc": "RC", "ws": "WS",
                "wzc": "WZC", "w1p": "W1P",
            }
            swacc = swacc_map.get(raw_access, raw_access.upper() if raw_access else "RW")
            # hwqe: HW write enable (default false, true for hrw/hwo)
            hwqe = f.get("hwqe", "true" if raw_hwaccess in ("hrw", "hwo") else "false")
            reg_fields_detail.append({
                "reg_name": r["name"],
                "reg_offset": reg_addr_map.get(r["name"], "0x000"),
                "field_name": f.get("name", ""),
                "bits": f.get("bits", ""),
                "access": raw_access,
                "hwaccess": raw_hwaccess,
                "swacc": swacc,
                "hwqe": hwqe,
                "reset": f.get("reset", "0"),
                "desc": f.get("desc", ""),
            })
    data["reg_fields_detail"] = reg_fields_detail
    data["num_registers"] = len(data["registers"])
    data["num_fields"] = len(reg_fields_detail)

    # ── Generated files registry ──
    data["generated_files"] = {
        "tb_top": "tb_top.sv",
        "env_pkg": f"{module.get('name', 'unknown')}_env_pkg.sv",
        "ral_block": f"{module.get('name', 'unknown')}_ral_block.sv",
        "interface_apb": "interface_apb.sv",
        "agent": f"{module.get('name', 'unknown')}_agent.sv",
        "sequencer": f"{module.get('name', 'unknown')}_sequencer.sv",
        "driver": f"{module.get('name', 'unknown')}_driver.sv",
        "monitor": f"{module.get('name', 'unknown')}_monitor.sv",
        "scoreboard": f"{module.get('name', 'unknown')}_scoreboard.sv",
        "base_seq": f"{module.get('name', 'unknown')}_base_seq.sv",
        "base_test": f"{module.get('name', 'unknown')}_base_test.sv",
        "coverage": f"{module.get('name', 'unknown')}_coverage.sv",
        "transaction_apb": "transaction_apb.sv",
        "env": f"{module.get('name', 'unknown')}_env.sv",
        "bfm": f"{module.get('name', 'unknown')}_bfm.sv",
    }

    # ── Access type normalization ──
    access_type_map = {
        "rw": "RW", "ro": "RO", "wo": "WO",
        "w1c": "W1C", "w1s": "W1S", "w1t": "W1T",
        "rw1c": "RW1C", "rc": "RC", "ws": "WS",
        "wzc": "WZC", "w1p": "W1P",
    }
    for f in reg_fields_detail:
        raw_access = f.get("access", "").lower()
        f["access_norm"] = access_type_map.get(raw_access, raw_access.upper() if raw_access else "RW")

    # ── Reserved address ranges ──
    reserved_ranges = []
    sorted_regs = sorted(
        [(r, int(reg_addr_map.get(r["name"], "0x000"), 16)) for r in data["registers"]],
        key=lambda x: x[1]
    )
    for i in range(len(sorted_regs) - 1):
        r1, addr1 = sorted_regs[i]
        r2, addr2 = sorted_regs[i + 1]
        if addr1 + 4 < addr2:
            reserved_ranges.append({
                "start_str": f"0x{addr1 + 4:04X}",
                "end_str": f"0x{addr2 - 1:04X}",
                "desc": f"reserved between {r1['name']} and {r2['name']}"
            })
    # Also add from last register to top of address space (assume 4K or addr_width-based)
    apb_if = data["apb"]
    addr_width = apb_if.get("addr_width", 12) if apb_if else 12
    last_addr_full = 1 << addr_width if addr_width else 0x1000
    if sorted_regs:
        last_reg = sorted_regs[-1]
        last_reg_addr = last_reg[1]
        if last_reg_addr + 4 < last_addr_full:
            reserved_ranges.append({
                "start_str": f"0x{last_reg_addr + 4:04X}",
                "end_str": f"0x{last_addr_full - 1:04X}",
                "desc": f"reserved above {last_reg[0]['name']}"
            })
    data["reserved_ranges"] = reserved_ranges

    # ── Parse APB steps from test scenario text ──
    for sc in data["test_scenarios"]:
        apb_steps = []
        seq_text = (sc.get("detail") or sc.get("sequence") or "")
        if isinstance(seq_text, list):
            seq_text = "\n".join(seq_text)
        if seq_text:
            import re
            lines = seq_text.split("\n")
            for line in lines:
                line = line.strip()
                if not line:
                    continue
                # READ_CHECK pattern
                m = re.match(r'(?i)read\s+(\w+).*?(?:→|->|=>|verify)\s*(0x[0-9a-fA-F]+)', line)
                if m:
                    apb_steps.append({"action": "READ_CHECK", "reg_name": m.group(1),
                                      "offset": reg_addr_map.get(m.group(1).upper(), "0x000"),
                                      "data": m.group(2)})
                    continue
                # READ pattern
                m = re.match(r'(?i)read\s+(\w+)', line)
                if m:
                    apb_steps.append({"action": "READ", "reg_name": m.group(1),
                                      "offset": reg_addr_map.get(m.group(1).upper(), "0x000")})
                    continue
                # WRITE with value
                m = re.match(r'(?i)write\s+(\w+)\s+(?:with|=)\s*(0x[0-9a-fA-F]+|\d+)', line)
                if m:
                    apb_steps.append({"action": "WRITE", "reg_name": m.group(1),
                                      "offset": reg_addr_map.get(m.group(1).upper(), "0x000"),
                                      "data": m.group(2)})
                    continue
                # SET pattern
                m = re.match(r'(?i)set\s+(\w+)\s*=\s*(0x[0-9a-fA-F]+|\d+)', line)
                if m:
                    apb_steps.append({"action": "WRITE", "reg_name": m.group(1),
                                      "offset": reg_addr_map.get(m.group(1).upper(), "0x000"),
                                      "data": m.group(2)})
                    continue
                # VERIFY pattern
                m = re.match(r'(?i)verify\s+(\w+)\s*=\s*(0x[0-9a-fA-F]+|\d+)', line)
                if m:
                    apb_steps.append({"action": "READ_CHECK", "reg_name": m.group(1),
                                      "offset": reg_addr_map.get(m.group(1).upper(), "0x000"),
                                      "data": m.group(2)})
                    continue
                # Reserved address read/write
                m = re.match(r'(?i)(?:read|write)\s+to?\s+(?:reserved\s+)?address\s+(0x[0-9a-fA-F]+)', line)
                if m:
                    addr = m.group(1)
                    action = "READ" if "read" in line.lower().split()[0] else "WRITE"
                    apb_steps.append({"action": action, "reg_name": f"reserved@{addr}",
                                      "offset": addr, "data": "0x00" if action == "WRITE" else ""})
                    continue
        sc["apb_steps"] = apb_steps

    return data


# ── Architect data loader (backward-compat) ──
def load_architect_data(out_dir):
    """Load architect YAML files generated by spec-analyzer."""
    import yaml
    result = {}
    ifcs_path = os.path.join(out_dir, "architect", "interface-list.yml")
    if os.path.exists(ifcs_path):
        result["interfaces"] = yaml.safe_load(open(ifcs_path, "r")).get("interfaces", [])
    reg_path = os.path.join(out_dir, "architect", "register-map.yml")
    if os.path.exists(reg_path):
        rm = yaml.safe_load(open(reg_path, "r"))
        result["module"] = rm.get("module", "unknown")
        result["registers"] = rm.get("registers", [])
    scenarios_path = os.path.join(out_dir, "architect", "test-scenarios.yml")
    if os.path.exists(scenarios_path):
        result["test_scenarios"] = yaml.safe_load(open(scenarios_path, "r")).get("test_scenarios", [])
    return result


def extract_module_name(out_dir):
    """Extract module name from architect data or contract files."""
    reg_path = os.path.join(out_dir, "architect", "register-map.yml")
    if os.path.exists(reg_path):
        import yaml
        rm = yaml.safe_load(open(reg_path, "r"))
        mod = rm.get("module", "")
        if mod:
            return mod
    contract_path = os.path.join(out_dir, ".contract_spec-analyzer.json")
    if os.path.exists(contract_path):
        c = json.load(open(contract_path, "r"))
        mod = c.get("module", {}).get("name", "")
        if mod:
            return mod
    return "unknown"
