#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""doc-gen — verification close report (protocol-agnostic)"""

import os, glob, argparse, sys
sys.path.insert(0, os.path.dirname(__file__))
from template_engine import build_spec_data

BASE_DIR = os.path.dirname(__file__)
parser = argparse.ArgumentParser()
parser.add_argument("--spec", default="")
parser.add_argument("--out", default=os.path.join(BASE_DIR, "..", "output"))
args = parser.parse_args()

SPEC_PATH = args.spec if args.spec else os.path.join(BASE_DIR, "..", "i2c_spec.yml")
if not os.path.exists(SPEC_PATH):
    SPEC_PATH = os.path.join(BASE_DIR, "..", "uart_spec.yml")
if not os.path.exists(SPEC_PATH):
    print(f"  [X] No spec file found"); sys.exit(1)

data = build_spec_data(SPEC_PATH)
module = data["module_name"]
OUT_DIR = os.path.abspath(args.out)
DOC_DIR = os.path.join(OUT_DIR, "docs")
os.makedirs(DOC_DIR, exist_ok=True)

# Count generated files
env_dir = os.path.join(OUT_DIR, "rtl", "verification", "env")
n_sv = len(glob.glob(os.path.join(env_dir, "**/*.sv"), recursive=True)) if os.path.exists(env_dir) else 0
n_if = len(glob.glob(os.path.join(env_dir, "interfaces", "*.sv"))) if os.path.exists(os.path.join(env_dir, "interfaces")) else 0
n_agent = len(glob.glob(os.path.join(env_dir, "agents", "*.sv"))) if os.path.exists(os.path.join(env_dir, "agents")) else 0
n_seq = len(glob.glob(os.path.join(env_dir, "sequences", "*.sv"))) if os.path.exists(os.path.join(env_dir, "sequences")) else 0
n_asrt = len(glob.glob(os.path.join(env_dir, "assertions", "*.sv"))) if os.path.exists(os.path.join(env_dir, "assertions")) else 0
n_sb = len(glob.glob(os.path.join(env_dir, "scoreboard", "*.sv"))) if os.path.exists(os.path.join(env_dir, "scoreboard")) else 0
n_cov = len(glob.glob(os.path.join(env_dir, "coverage", "*.sv"))) if os.path.exists(os.path.join(env_dir, "coverage")) else 0

ifaces = ", ".join(i["type"] for i in data["interfaces"])
n_regs = len(data["registers"])
n_tests = len(data["test_scenarios"])

report = f"""# {module.upper()} Verification Close Report

**Generated:** {data['date']}
**Module:** {module} ({data['module_desc']})
**Spec:** {os.path.basename(SPEC_PATH)}

## Summary

| Metric | Value |
|--------|-------|
| Interfaces | {ifaces} |
| Registers | {n_regs} |
| Test Scenarios | {n_tests} |
| SV Files Generated | {n_sv} |

## Generated Environment

| Category | Count |
|----------|-------|
| Interface files | {n_if} |
| Agent files | {n_agent} |
| Sequence files | {n_seq} |
| Assertion files | {n_asrt} |
| Scoreboard files | {n_sb} |
| Coverage files | {n_cov} |

## Test Scenarios

"""
for i, sc in enumerate(data["test_scenarios"]):
    report += f"{i+1}. **{sc.get('name','?')}** — {sc.get('description','')}\n"

report += f"""
## Key Files

- Testbench: `rtl/verification/env/tb_top.sv`
- Environment: `rtl/verification/env/{module}_env.sv`
- Package: `rtl/verification/env/env_pkg.sv`
- Makefile: `rtl/verification/env/sim/Makefile`

---
*Auto-generated by digital-verify-pro*
"""

path = os.path.join(DOC_DIR, "verification-close-report.md")
with open(path, "w", encoding="utf-8") as f:
    f.write(report)

print(f"{'='*60}")
print(f"  {module.upper()} PIPELINE COMPLETE!")
print(f"  Total SV: {n_sv} files")
print(f"  Breakdown: {n_if} if + {n_agent} agent + {n_seq} seq + {n_asrt} asrt + {n_sb} sb + {n_cov} cov")
print(f"  Docs: docs/verification-close-report.md")
print(f"{'='*60}")

from validators import validate_doc_gen
result = validate_doc_gen(OUT_DIR)
for iss in result["issues"]:
    print(f"  [{iss['severity']}] {iss.get('file','')}: {iss['message']}")
if not result["passed"]:
    print(f"  [VALIDATION] doc-gen FAILED"); sys.exit(1)
else:
    print(f"  [VALIDATION] doc-gen PASSED")
