#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
sw-header-gen — C header generation from spec YAML.

Inspired by OpenTitan's reggen.py which outputs:
- RTL (sv)
- UVM RAL
- C header (h)
- JSON metadata
- RST documentation

Generates:
- <module>.h   — Register address macros + field bit definitions
- <module>.h   — Driver helper inline functions

One spec → all outputs. No hand-maintained headers.
"""

import os, sys, argparse

BASE_DIR = os.path.dirname(__file__)
sys.path.insert(0, BASE_DIR)
from template_engine import build_spec_data

parser = argparse.ArgumentParser()
parser.add_argument("--spec", default="")
parser.add_argument("--out", default=os.path.join(BASE_DIR, "..", "output"))
args = parser.parse_args()

SPEC_PATH = args.spec
if not SPEC_PATH:
    for c in ["i2c_spec.yml", "pcie_ep_spec.yml", "arm_pl061_gpio.yml"]:
        full = os.path.join(BASE_DIR, "..", c)
        if os.path.exists(full):
            SPEC_PATH = full
            break
if not SPEC_PATH or not os.path.exists(SPEC_PATH):
    print("  [X] No spec file found")
    sys.exit(1)

data = build_spec_data(SPEC_PATH)
module = data["module_name"]
date = data["date"]
OUT_DIR = os.path.abspath(args.out)
SW_DIR = os.path.join(OUT_DIR, "sw")
os.makedirs(SW_DIR, exist_ok=True)

regs = data["registers"]
reg_addr_map = data["reg_addr_map"]
reg_fields_detail = data["reg_fields_detail"]

print(f"{'='*60}")
print(f"  SW-HEADER-GEN — {module.upper()} C Header")
print(f"  {len(regs)} registers, {len(reg_fields_detail)} fields")
print(f"{'='*60}")

# ── Generate C header ──
lines = []
lines.append(f"// {date}")
lines.append(f"// Auto-generated by digital-verify-pro sw-header-gen")
lines.append(f"// Register map for {module}")
lines.append(f"// Source: {os.path.basename(SPEC_PATH)}")
lines.append(f"")
lines.append(f"#ifndef _${module.upper()}_H_")
lines.append(f"#define _${module.upper()}_H_")
lines.append(f"")
lines.append(f"#include <stdint.h>")
lines.append(f"")
lines.append(f"// Base address (to be defined by platform)")
lines.append(f"// #define {module.upper()}_BASE_ADDR 0xXXXX_XXXX")
lines.append(f"")

# Register address offsets
lines.append(f"// === Register Address Map ===")
lines.append(f"")
for r in regs:
    name = r["name"]
    off = reg_addr_map.get(name, "0x000")
    desc = r.get("description", "").split("\n")[0] if r.get("description") else ""
    lines.append(f"#define {module.upper()}_{name.upper()}_OFFSET  {off}  // {desc}")

lines.append(f"")
lines.append(f"// === Register Field Bit Definitions ===")
lines.append(f"")

# Per-register field definitions
for r in regs:
    rname = r["name"]
    off = reg_addr_map.get(rname, "0x000")
    fields = r.get("fields", [])
    if not fields:
        continue
    lines.append(f"// {rname} (offset {off})")
    for f in fields:
        fname = f.get("name", "")
        if not fname:
            continue
        bits_raw = f.get("bits", "[0]").strip("[]")
        access = f.get("access", "rw")
        reset = f.get("reset", "0")
        desc = f.get("desc", "")

        # Parse bit range
        if ":" in bits_raw:
            msb, lsb = bits_raw.split(":")
            msb, lsb = int(msb), int(lsb)
            width = msb - lsb + 1
            mask = ((1 << width) - 1) << lsb
        else:
            lsb = int(bits_raw)
            width = 1
            mask = 1 << lsb

        # Field bitmask
        lines.append(f"#define {module.upper()}_{rname.upper()}_{fname.upper()}_MASK  0x{mask:08X}U")
        lines.append(f"#define {module.upper()}_{rname.upper()}_{fname.upper()}_OFFSET  {lsb}")
        lines.append(f"#define {module.upper()}_{rname.upper()}_{fname.upper()}_WIDTH  {width}")
        # Access type
        acc_comment = {"rw": "R/W", "ro": "R/O", "wo": "W/O", "w1c": "W1C", "rc": "RC"}.get(access, access.upper())
        reset_comment = f"reset=0x{int(reset,16) if reset.startswith('0x') else int(reset):X}" if reset != "0" else ""
        lines.append(f"//   access={acc_comment}  {desc}  {reset_comment}")
    lines.append(f"")

# ── Driver inline helpers ──
lines.append(f"// === Driver Helpers ===")
lines.append(f"")
lines.append(f"// Read register at given address")
lines.append(f"static inline uint32_t {module}_read(uint32_t base, uint32_t offset) {{")
lines.append(f"    return *(volatile uint32_t *)(base + offset);")
lines.append(f"}}")
lines.append(f"")
lines.append(f"// Write register at given address")
lines.append(f"static inline void {module}_write(uint32_t base, uint32_t offset, uint32_t val) {{")
lines.append(f"    *(volatile uint32_t *)(base + offset) = val;")
lines.append(f"}}")

# Field-level read/write helpers
lines.append(f"")
lines.append(f"// Read field value from register")
lines.append(f"static inline uint32_t {module}_field_read(uint32_t base, uint32_t offset, uint32_t mask, int shift) {{")
lines.append(f"    return ({module}_read(base, offset) >> shift) & (mask >> shift);")
lines.append(f"}}")
lines.append(f"")
lines.append(f"// Write field value to register (read-modify-write)")
lines.append(f"static inline void {module}_field_write(uint32_t base, uint32_t offset, uint32_t mask, int shift, uint32_t val) {{")
lines.append(f"    uint32_t tmp = {module}_read(base, offset);")
lines.append(f"    tmp &= ~mask;")
lines.append(f"    tmp |= (val << shift) & mask;")
lines.append(f"    {module}_write(base, offset, tmp);")
lines.append(f"}}")

lines.append(f"")
lines.append(f"#endif  // _${module.upper()}_H_")
lines.append(f"")

# Write header
header_path = os.path.join(SW_DIR, f"{module}.h")
with open(header_path, "w", encoding="utf-8") as f:
    f.write("\n".join(lines).encode("ascii", "replace").decode("ascii"))
print(f"  [GEN] sw/{module}.h  ({len(regs)} regs, {len(reg_fields_detail)} fields)")

# ── Validation ──
try:
    from validators import validate_sw_header
    result = validate_sw_header(SW_DIR, module)
    for iss in result.get("issues", []):
        print(f"  [{iss['severity']}] {iss.get('file','')}: {iss['message']}")
    if result.get("passed", True):
        print(f"  [VALIDATION] sw-header-gen PASSED")
except ImportError:
    pass

print(f"{'='*60}\n  SW-HEADER-GEN COMPLETE ({module.upper()})\n{'='*60}")
