#!/usr/bin/env python3
"""
tb_gen — TestBench Generator v3

从 test_plan.yml 读取测试点分解表，为每个测试点生成：
  1. UVM test sequence（继承 base_seq）
  2. 追加到 regression_list.py

用法：
  python tb_gen.py --plan verify/test_plan.yml --out output/tests
  python tb_gen.py --plan verify/test_plan.yml --regression verify/regression_list.py
"""
import os, sys, yaml, json, argparse, re
from datetime import datetime
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(BASE_DIR))
from template_engine import render_to_file

SEQ_TEMPLATE = '''\
// {{ description }}
// Auto-generated by tb_gen on {{ timestamp }}
// Feature: {{ feature }} | Stage: {{ stage }}

class {{ module }}_{{ seq_name }}_seq extends {{ base_seq }};

    `uvm_object_utils({{ module }}_{{ seq_name }}_seq)

    function new(string name = "{{ module }}_{{ seq_name }}_seq");
        super.new(name);
    endfunction

    virtual task body();
        `uvm_info(get_type_name(), "Starting: {{ description }}", UVM_LOW)
        // TODO: implement stimulus based on test_plan description
        // {{ stimulus }}
        `uvm_info(get_type_name(), "Completed: {{ description }}", UVM_LOW)
    endtask

endclass
'''


def parse_args():
    ap = argparse.ArgumentParser(description="tb_gen — TestBench Generator v3")
    ap.add_argument("--plan", required=True, help="Path to test_plan.yml")
    ap.add_argument("--out", default="output/tests", help="Output directory for generated sequences")
    ap.add_argument("--module", default="i2c", help="Module name prefix for generated files")
    ap.add_argument("--regression", help="Path to regression_list.py to update")
    ap.add_argument("--dry-run", action="store_true", help="Print what would be generated without writing")
    return ap.parse_args()


def load_test_plan(path):
    with open(path, "r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def gen_seq_name(tp_id, feature):
    """生成 UVM sequence 名称，用 testpoint id 保证唯一"""
    # tp_id like REG_RW_001 -> reg_rw_001
    return tp_id.lower().replace("_", "_")


def generate_sequence(args, tp, module):
    """为单个测试点生成 UVM sequence 文件"""
    seq_name = gen_seq_name(tp["id"], tp.get("feature", "gen"))
    base_seq = tp.get("base_seq", f"{module}_base_seq")
    filename = f"{module}_{seq_name.lower()}_seq.sv"
    filepath = os.path.join(args.out, filename)

    context = {
        "module": module,
        "seq_name": seq_name,
        "base_seq": base_seq,
        "description": tp.get("description", ""),
        "feature": tp.get("feature", ""),
        "stage": tp.get("stage", ""),
        "stimulus": tp.get("stimulus", ""),
        "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
    }

    if args.dry_run:
        print(f"  [DRY] {filepath}")
        return None

    os.makedirs(args.out, exist_ok=True)
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(render_template(SEQ_TEMPLATE, context))
    print(f"  [GEN] {filepath}")
    return {
        "name": f"{module}_{seq_name.lower()}",
        "filename": filename,
        "feature_id": tp["id"],
        "feature": tp.get("feature", ""),
        "priority": "p0" if tp.get("stage") == "v1_smoke" else "p1" if tp.get("stage") == "v2_stress" else "p2",
    }


def render_template(template, context):
    """简单的模板渲染（可用 Jinja2 替代）"""
    import re
    result = template
    for key, val in context.items():
        result = result.replace("{{ " + key + " }}", str(val))
    return result


def update_regression_list(path, generated_cases):
    """将生成的 case 追加到 regression_list.py 的 auto_cases 段"""
    auto_entries = []
    for c in generated_cases:
        auto_entries.append(f"    \"{c['name']}\",\n")

    if not os.path.exists(path):
        # 创建新的 regression_list.py
        content = f'''"""回归清单 — 由 tb_gen 自动生成 + 手动追加"""
import os

# --- 自动生成部分（tb_gen 覆盖刷新）---
auto_cases = [
{''.join(auto_entries) }]

# --- 手动追加部分（tb_gen 不覆盖）---
manual_cases = []

ALL_CASES = auto_cases + manual_cases


def active_cases():
    return [c for c in ALL_CASES if not c.startswith("#")]
'''
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        print(f"  [REGRESSION] Created {path} ({len(auto_entries)} auto cases)")
        return

    # 读取现有文件，替换 auto_cases 段
    with open(path, "r", encoding="utf-8") as f:
        content = f.read()

    # 替换 auto_cases 列表
    start_marker = "auto_cases = ["
    end_marker = "]"
    start = content.find(start_marker)
    if start < 0:
        print(f"  [WARN] auto_cases not found in {path}, appending")
        content += f"\n# auto cases (tb_gen)\nauto_cases = [\n{''.join(auto_entries)}]\n"
    else:
        end = content.find(end_marker, start + len(start_marker))
        if end >= 0:
            new_section = start_marker + "\n" + "".join(auto_entries) + "]"
            content = content[:start] + new_section + content[end + 1:]
        else:
            content += f"\n# auto cases\nauto_cases = [\n{''.join(auto_entries)}]\n"

    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"  [REGRESSION] Updated {path} ({len(auto_entries)} auto cases)")


def main():
    args = parse_args()
    plan = load_test_plan(args.plan)

    module = args.module
    testpoints = plan.get("testpoints", [])
    print(f"[tb_gen] {len(testpoints)} testpoints from {args.plan}")

    generated = []
    for tp in testpoints:
        result = generate_sequence(args, tp, module)
        if result:
            generated.append(result)

    if args.regression and not args.dry_run:
        update_regression_list(args.regression, generated)

    print(f"\n[DONE] Generated {len(generated)} sequences")
    return 0


if __name__ == "__main__":
    sys.exit(main())
