#!/usr/bin/env python3
"""
tb_gen — TestBench Generator v3

从 test_plan.yml 读取测试点分解表，为每个测试点生成：
  1. UVM test sequence（继承 base_seq）
  2. 追加到 regression_list.py

用法：
  python tb_gen.py --plan verify/test_plan.yml --out output/tests
  python tb_gen.py --plan verify/test_plan.yml --regression verify/regression_list.py
"""
import os, sys, yaml, json, argparse, re
from datetime import datetime
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(BASE_DIR))
from template_engine import render_to_file

SEQ_TEMPLATE = '''\
// {{ description }}
// Auto-generated by tb_gen on {{ timestamp }}
// Feature: {{ feature }} | Stage: {{ stage }}

class {{ module }}_{{ seq_name }}_seq extends {{ base_seq }};

    `uvm_object_utils({{ module }}_{{ seq_name }}_seq)

    function new(string name = "{{ module }}_{{ seq_name }}_seq");
        super.new(name);
    endfunction

    virtual task body();
        `uvm_info(get_type_name(), "Starting: {{ description }}", UVM_LOW)
        // TODO: implement stimulus based on test_plan description
        // {{ stimulus }}
        `uvm_info(get_type_name(), "Completed: {{ description }}", UVM_LOW)
    endtask

endclass
'''


def parse_args():
    ap = argparse.ArgumentParser(description="tb_gen — TestBench Generator v3")
    ap.add_argument("--plan", required=True, help="Path to test_plan.yml")
    ap.add_argument("--spec", help="Spec file path")
    ap.add_argument("--out", default="output/tests", help="Output directory for generated sequences")
    ap.add_argument("--module", default="i2c", help="Module name prefix for generated files")
    ap.add_argument("--regression", help="Path to regression_list.py to update")
    ap.add_argument("--dry-run", action="store_true", help="Print what would be generated without writing")
    return ap.parse_args()


def load_test_plan(path):
    with open(path, "r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def gen_seq_name(tp_id, feature):
    """生成 UVM sequence 名称，用 testpoint id 保证唯一"""
    # tp_id like REG_RW_001 -> reg_rw_001
    return tp_id.lower().replace("_", "_")


def generate_sequence(args, tp, module):
    """为单个测试点生成 UVM sequence 文件"""
    seq_name = gen_seq_name(tp["id"], tp.get("feature", "gen"))
    base_seq = tp.get("base_seq", f"{module}_base_seq")
    filename = f"{module}_{seq_name.lower()}_seq.sv"
    filepath = os.path.join(args.out, filename)

    context = {
        "module": module,
        "seq_name": seq_name,
        "base_seq": base_seq,
        "description": tp.get("description", ""),
        "feature": tp.get("feature", ""),
        "stage": tp.get("stage", ""),
        "stimulus": tp.get("stimulus", ""),
        "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
    }

    if args.dry_run:
        print(f"  [DRY] {filepath}")
        return None

    os.makedirs(args.out, exist_ok=True)
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(render_template(SEQ_TEMPLATE, context))
    print(f"  [GEN] {filepath}")
    return {
        "name": f"{module}_{seq_name.lower()}",
        "filename": filename,
        "feature_id": tp["id"],
        "feature": tp.get("feature", ""),
        "priority": "p0" if tp.get("stage") == "v1_smoke" else "p1" if tp.get("stage") == "v2_stress" else "p2",
    }


def render_template(template, context):
    """简单的模板渲染（可用 Jinja2 替代）"""
    import re
    result = template
    for key, val in context.items():
        result = result.replace("{{ " + key + " }}", str(val))
    return result



def update_regression_list(path, generated_cases):
    """Update regression_list.py with generated cases."""
    import os
    entries = []
    for c in generated_cases:
        entries.append('    "' + c['name'] + '",\n')
    
    if not os.path.isfile(path):
        with open(path, 'w', encoding='utf-8') as f:
            f.write('"""Regression list."""\n')
            f.write('auto_cases = [\n')
            for e in entries:
                f.write(e)
            f.write(']\n')
            f.write('manual_cases = []\n')
            f.write('ALL_CASES = auto_cases + manual_cases\n')
        print('  [REGRESSION] Created ' + path)
        return
    
    with open(path, 'r', encoding='utf-8') as f:
        lines = f.readlines()
    
    new_lines = []
    in_auto = False
    found = False
    for line in lines:
        if 'auto_cases = [' in line:
            in_auto = True
            found = True
            new_lines.append(line)
            for e in entries:
                new_lines.append(e)
            new_lines.append(']\n')
        elif in_auto and line.strip() == ']':
            in_auto = False
            continue
        elif not in_auto:
            new_lines.append(line)
    
    if found:
        with open(path, 'w', encoding='utf-8') as f:
            f.writelines(new_lines)
        print('  [REGRESSION] Updated ' + path)

def main():
    args = parse_args()
    plan = load_test_plan(args.plan)

    module = args.module
    testpoints = plan.get("testpoints", [])
    print(f"[tb_gen] {len(testpoints)} testpoints from {args.plan}")

    generated = []
    for tp in testpoints:
        result = generate_sequence(args, tp, module)
        if result:
            generated.append(result)

    if args.regression and not args.dry_run:
        update_regression_list(args.regression, generated)

    print(f"\n[DONE] Generated {len(generated)} sequences")
    return 0


if __name__ == "__main__":
    sys.exit(main())
