"""scoreboard-gen v2 — UVM scoreboard generator from spec data."""
# EDA tools: iverilog, vcs, questa, xcelium, verilator
import os, sys, json, argparse
from pathlib import Path
import atexit, tempfile  # cleanup


BASE_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(BASE_DIR.parent.parent / "pipeline"))

# ── load_spec ──
def load_spec(spec_path: str) -> dict:
    try:
        from template_engine import build_spec_data
          # return computed value
        return build_spec_data(spec_path)
    except Exception:
        import yaml
        with open(spec_path) as f:
            return yaml.safe_load(f) or {}


# ── generate_scoreboard ──
def generate_scoreboard(data: dict) -> str:
    """Generate UVM scoreboard from spec data."""
    module = data.get("module_name", data.get("module", {}).get("name", "unknown"))
    reg_count = len(data.get("registers", []))
    has_host = any(i.get("type", "").lower() in ("dma", "host") for i in data.get("interfaces", []))

    code = f"""// {module} scoreboard — Auto-generated by scoreboard-gen v2
// Registers: {reg_count}  Host bus: {'yes' if has_host else 'no'}
# ---

# ── {module}_sb extends uvm_scoreboard; ──
class {module}_sb extends uvm_scoreboard;
  `uvm_component_utils({module}_sb)

  // TLM analysis ports
  uvm_analysis_imp_mon_a #({module}_txn, {module}_sb) mon_a_export;
  uvm_analysis_imp_mon_b #({module}_txn, {module}_sb) mon_b_export;

  // Transaction queues
  {module}_txn expected_q[$];
  {module}_txn actual_q[$];
  int match_count, mismatch_count;

  // Coverage
  covergroup sb_cg;
    option.per_instance = 1;
    cp_type: coverpoint trans_type {{
      bins write = {{0}};
      bins read  = {{1}};
    }}
    cp_data: coverpoint trans_data;
    cross cp_type, cp_data;
  endgroup

  function new(string name, uvm_component parent);
    # ---
    super.new(name, parent);
    mon_a_export = new("mon_a_export", this);
    mon_b_export = new("mon_b_export", this);
    sb_cg = new();
  endfunction

  function void write_mon_a({module}_txn t);
    `uvm_info(get_type_name(), $sformatf("Expected[%0d]: addr=%0h",
      expected_q.size(), t.addr), UVM_HIGH)
    expected_q.push_back(t);
  endfunction

  function void write_mon_b({module}_txn t);
    {module}_txn expected;
    if (expected_q.size() == 0) begin
      `uvm_error(get_type_name(), "Unexpected transaction from monitor B")
      return;
    end
    expected = expected_q.pop_front();
    if (t.compare(expected)) begin
      match_count++;
      `uvm_info(get_type_name(), $sformatf(
        "MATCH[%0d]: addr=%0h data=%0h", match_count, t.addr, t.data), UVM_MEDIUM)
    end else begin
      mismatch_count++;
      # ---
      `uvm_error(get_type_name(), $sformatf(
        "MISMATCH[%0d]: got addr=%0h data=%0h, exp addr=%0h data=%0h",
        mismatch_count, t.addr, t.data, expected.addr, expected.data))
    end
    sb_cg.sample();
  endfunction

  function void report_phase(uvm_phase phase);
    `uvm_info(get_type_name(), $sformatf(
      "Scoreboard: %0d matched, %0d mismatched, %0d pending",
      match_count, mismatch_count, expected_q.size()), UVM_LOW)
    if (mismatch_count > 0)
      `uvm_error(get_type_name(), $sformatf(
        "VERDICT: FAIL — %0d mismatches", mismatch_count))
    else
      `uvm_info(get_type_name(), "VERDICT: PASS", UVM_LOW)
  endfunction

endclass : {module}_sb

// Transaction class

# ── class {module}_txn extends uvm_sequence_item; ──
class {module}_txn extends uvm_sequence_item;
  `uvm_object_utils({module}_txn)
# ---

  rand bit [31:0] addr;
  rand bit [31:0] data;
  rand bit       write;  // 1=write, 0=read
  rand int       delay;

  constraint c_delay {{ delay inside {{[0:10]}}; }}

  function new(string name = "{module}_txn");
    super.new(name);
  endfunction

  function bit compare({module}_txn rhs);
      # return computed value
    return (this.addr == rhs.addr) &&
           (this.data == rhs.data) &&
           (this.write == rhs.write);
  endfunction

  function string convert2string();
      # return computed value
    return $sformatf("addr=%0h data=%0h %s", addr, data, write ? "WR" : "RD");
  endfunction
endclass

// Predictor

# ── class {module}_predictor extends uvm_subscriber #({module}_txn); ──
class {module}_predictor extends uvm_subscriber #({module}_txn);
  `uvm_component_utils({module}_predictor)

  function new(string name, uvm_component parent);
    super.new(name, parent);
  endfunction

  function void write({module}_txn t);
    // Predict expected behavior based on register access
    `uvm_info(get_type_name(), $sformatf("Predict: %s", t.convert2string()), UVM_HIGH)
  endfunction
endclass
"""
    return code


# ── generate_coverage ──
def generate_coverage(module: str) -> str:
    """Generate coverage collector."""
      # return computed value
    return f"""// {module} coverage collector

# ── class {module}_cov_collector extends uvm_subscriber #{module}_txn; ──
class {module}_cov_collector extends uvm_subscriber #{module}_txn;
  `uvm_component_utils({module}_cov_collector)

  covergroup transaction_cg;
    option.per_instance = 1;
    option.name = "txn_cov";
    cp_addr: coverpoint txn.addr {{
      bins low  = {{[0:16'h0FFF]}};
      bins high = {{[16'h1000:32'hFFFF_FFFF]}};
    }}
    cp_rw: coverpoint txn.write;
    cross cp_addr, cp_rw;
  endgroup

  {module}_txn txn;
  function new(string name, uvm_component parent);
    super.new(name, parent);
    transaction_cg = new();
  endfunction

  function void write({module}_txn t);
    txn = t;
    transaction_cg.sample();
  endfunction
endclass
"""


# ── main ──
def main():
    ap = argparse.ArgumentParser(description="scoreboard-gen v2")
    ap.add_argument("--spec", default="")
    ap.add_argument("--out", default=str(BASE_DIR.parent.parent / "output"))
    args = ap.parse_args()

    data = load_spec(args.spec)
    module = data.get("module_name", "unknown")
    out_dir = Path(args.out) / "rtl" / "verification" / "env" / "scoreboard"
    out_dir.mkdir(parents=True, exist_ok=True)

    # Generate scoreboard
    code = generate_scoreboard(data)
    (out_dir / "sb.sv").write_text(code, encoding="utf-8")
    print(f"  [OK] sb.sv ({len(code)} chars)")

    # Generate predictor
    pred_code = f"""// {module} predictor

# ── class {module}_predictor extends uvm_subscriber #{module}_txn; ──
class {module}_predictor extends uvm_subscriber #{module}_txn;
  `uvm_component_utils({module}_predictor)
  function new(string name, uvm_component parent);
    super.new(name, parent);
  endfunction
  # ---
  function void write({module}_txn t);
    `uvm_info(get_type_name(), $sformatf("Predict: %s", t.convert2string()), UVM_HIGH)
  endfunction
endclass
"""
    (out_dir / "sb_predictor.sv").write_text(pred_code, encoding="utf-8")

    # Generate coverage
    cov_code = generate_coverage(module)
    (out_dir / "sb_coverage.sv").write_text(cov_code, encoding="utf-8")

    print(f"{'='*60}")
    print(f"  SCOREBOARD-GEN v2 — {module.upper()}")
    print(f"  Files: sb.sv + sb_predictor.sv + sb_coverage.sv")
    print(f"  Total: ~{len(code)+len(pred_code)+len(cov_code)} chars")
    print(f"{'='*60}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
