#!/usr/bin/env python3
"""
formal_check_gen.py - Formal Property Check Generator for SymbiYosys

Generates:
- SystemVerilog Assertions (SVA) from RTL analysis
- SymbiYosys .sby configuration files for formal verification
- Cover properties for reachability analysis
- Assume properties for input constraints
- Assert properties for output correctness
"""

import re
import os
import sys
from typing import List, Dict, Optional
from dataclasses import dataclass, field


@dataclass
class FormalProperty:
    name: str
    kind: str  # assert, assume, cover
    expression: str
    clock: str = ""
    reset: str = ""
    category: str = ""  # safety, liveness, reachability
    description: str = ""


@dataclass
class FormalCheckConfig:
    module_name: str
    depth: int = 20
    engine: str = "smtbmc"  # smtbmc, abc, aiger, yices, z3
    properties: List[FormalProperty] = field(default_factory=list)
    rtl_files: List[str] = field(default_factory=list)

    def to_sby(self) -> str:
        """Generate SymbiYosys .sby configuration."""
        lines = []
        lines.append(f"[options]")
        lines.append(f"mode bmc")
        lines.append(f"depth {self.depth}")
        lines.append(f"")
        lines.append(f"[engines]")
        lines.append(f"{self.engine}")
        lines.append(f"")
        lines.append(f"[script]")
        for rtl in self.rtl_files:
            lines.append(f"read -formal {rtl}")
        lines.append(f"prep -top {self.module_name}")
        lines.append(f"")
        lines.append(f"[files]")
        for rtl in self.rtl_files:
            lines.append(os.path.basename(rtl))
        lines.append(f"")
        return "\n".join(lines)

    def to_sva_module(self) -> str:
        """Generate SVA properties as a standalone Verilog module."""
        lines = []
        lines.append(f"// Formal properties for {self.module_name}")
        lines.append(f"// Generated by formal_check_gen.py")
        lines.append(f"// Engine: {self.engine}, Depth: {self.depth}")
        lines.append(f"")
        lines.append(f"`ifdef FORMAL")
        lines.append(f"module {self.module_name}_formal_check(")
        # Add top-level ports (simplified)
        lines.append(f"    input logic clk,")
        lines.append(f"    input logic rst_n")
        lines.append(f");")
        lines.append(f"")
        lines.append(f"    // Bind to DUT")
        lines.append(f"    {self.module_name} dut (.*);")
        lines.append(f"")
        lines.append(f"    // Default assumptions")
        if self.properties:
            lines.append(f"    //  Formal Properties ({len(self.properties)} total)")
            for i, prop in enumerate(self.properties):
                lines.append(f"    {prop.kind}_property__{prop.name}:")
                if prop.clock:
                    lines.append(f"        {prop.kind} property (@(posedge {prop.clock}) disable iff (!{prop.reset})")
                else:
                    lines.append(f"        {prop.kind} property (@(posedge clk) disable iff (!rst_n)")
                lines.append(f"            {prop.expression});")
                lines.append(f"")
        else:
            lines.append(f"    // Placeholder - add properties above")
            lines.append(f"    // Example:")
            lines.append(f"    // assert property (@(posedge clk) disable iff (!rst_n) ...);")

        lines.append(f"endmodule")
        lines.append(f"`endif // FORMAL")
        return "\n".join(lines)


class FormalChecker:
    """Generate formal verification properties from RTL analysis."""

    def __init__(self, rtl_path: str = ""):
        self.rtl_path = rtl_path
        self.rtl_content = ""
        self.module_name = "unknown"
        self.signals: Dict = {}
        self.always_blocks: List[str] = []
        self.assignments: List[str] = []
        self.clock_signal = "clk"
        self.reset_signal = "rst_n"

        if rtl_path and os.path.exists(rtl_path):
            with open(rtl_path) as f:
                self.rtl_content = f.read()
            self._parse_rtl()

    def _parse_rtl(self):
        """Parse RTL to extract structural information for property generation."""
        content = self.rtl_content

        # Module name
        m = re.search(r'module\s+(\w+)', content)
        if m:
            self.module_name = m.group(1)

        # Ports (extract from module declaration only)
        m_mod = re.search(r'module\s+\w+\s*\((.*?)\);', content, re.IGNORECASE | re.DOTALL)
        port_area = m_mod.group(1) if m_mod else ''
        if port_area:
            port_pat = re.compile(
                r'(input|output|inout)\s+(reg|wire)?\s*(?:\[(\d+:\d+)\])?\s*(\w+)',
                re.IGNORECASE
            )
            for part in port_area.split(','):
                m = port_pat.match(part.strip())
                if m:
                    self.signals[m.group(4)] = {
                        "direction": m.group(1).lower(),
                        "type": (m.group(2) or "wire").strip(),
                        "width": (m.group(3) or "").strip(),
                    }

        # Always blocks
        block_pat = re.compile(
            r'always\s*@\s*\((.*?)\)\s*(?:\*|\+|)\s*begin\s*(.*?)\s*end',
            re.IGNORECASE | re.DOTALL
        )
        self.always_blocks = [m.group() for m in block_pat.finditer(content)]

        # Continuous assignments
        assign_pat = re.compile(r'assign\s+(\w+(?:\s*\[.*?\])?)\s*=\s*(.+?);', re.IGNORECASE)
        self.assignments = [m.group() for m in assign_pat.finditer(content)]

        # Detect clock and reset
        for name in self.signals:
            nl = name.lower()
            if "clk" in nl:
                self.clock_signal = name
            if "rst" in nl:
                self.reset_signal = name

    def generate_properties(self) -> List[FormalProperty]:
        """Generate formal properties from RTL analysis."""
        props: List[FormalProperty] = []
        content = self.rtl_content

        # 1. Register stability (sequential)
        reg_assign_pat = re.compile(
            r'(\w+)\s*<=\s*(.+?);',
            re.IGNORECASE
        )
        regs = []
        for m in reg_assign_pat.finditer(content):
            reg_name = m.group(1).strip()
            expr = m.group(2).strip()
            # Skip common non-register names
            if reg_name.lower() in ("", "clk", "rst_n", "reset"):
                continue
            regs.append((reg_name, expr))

        for reg_name, expr in regs[:5]:  # Limit to 5 reg properties
            props.append(FormalProperty(
                name=f"{reg_name}_stability",
                kind="assert",
                expression=f"##1 $stable({reg_name}) || ({reg_name} == $past({reg_name} + 1)) || ({reg_name} == $past({reg_name} - 1))",
                clock=self.clock_signal,
                reset=self.reset_signal,
                category="safety",
                description=f"Register {reg_name} stability check",
            ))

        # 2. Output driven (combinational) - outputs must be driven
        for name, info in self.signals.items():
            if info["direction"] == "output":
                props.append(FormalProperty(
                    name=f"{name}_driven",
                    kind="cover",
                    expression=f"$rose({name}) || $fell({name})",
                    clock=self.clock_signal,
                    reset=self.reset_signal,
                    category="reachability",
                    description=f"Output {name} can toggle",
                ))

        # 3. X/Z propagation check
        for name in list(self.signals.keys())[:5]:
            props.append(FormalProperty(
                name=f"{name}_no_x",
                kind="assert",
                expression=f"!$isunknown({name})",
                clock=self.clock_signal,
                reset=self.reset_signal,
                category="safety",
                description=f"Signal {name} has no X/Z values",
            ))

        # 4. One-hot encoding for FSM (detect case statements)
        case_pat = re.compile(
            r'case\s*\((\w+)\)\s*(.*?)\s*endcase',
            re.IGNORECASE | re.DOTALL
        )
        for m in case_pat.finditer(content):
            case_var = m.group(1)
            states = re.findall(r"(\w+)\s*:", m.group(2))
            if len(states) >= 2:
                props.append(FormalProperty(
                    name=f"{case_var}_onehot",
                    kind="assert",
                    expression=f"$onehot0({{{', '.join(states[:5])}}})",
                    clock=self.clock_signal,
                    reset=self.reset_signal,
                    category="safety",
                    description=f"FSM {case_var} one-hot encoding",
                ))
                # Reachability: each state reachable
                for state in states[:5]:
                    props.append(FormalProperty(
                        name=f"reach_{case_var}_{state}",
                        kind="cover",
                        expression=f"({case_var} == {state})",
                        clock=self.clock_signal,
                        reset=self.reset_signal,
                        category="reachability",
                        description=f"FSM state {state} reachable",
                    ))

        # 5. Overflow/underflow for arithmetic
        if any(op in content for op in ['+', '-']):
            add_sub = re.findall(r'(\w+)\s*(?:<=|=)\s*(\w+)\s*([+-])\s*(\w+)', content)
            for dst, a, op, b in add_sub[:3]:
                props.append(FormalProperty(
                    name=f"{dst}_no_overflow",
                    kind="assert",
                    expression=f"$signed({dst}) == ($signed({a}) {op} $signed({b}))",
                    clock=self.clock_signal,
                    reset=self.reset_signal,
                    category="safety",
                    description=f"No overflow for {dst} = {a} {op} {b}",
                ))

        return props

    def generate_config(self, depth: int = 20, engine: str = "smtbmc") -> FormalCheckConfig:
        """Generate complete formal check configuration."""
        props = self.generate_properties()
        config = FormalCheckConfig(
            module_name=self.module_name,
            depth=depth,
            engine=engine,
            properties=props,
            rtl_files=[self.rtl_path] if self.rtl_path else [],
        )
        return config

    def generate_sva(self, config: FormalCheckConfig) -> str:
        """Generate the SVA bind module."""
        return config.to_sva_module()

    def generate_sby(self, config: FormalCheckConfig) -> str:
        """Generate the SymbiYosys .sby file."""
        return config.to_sby()

    def generate_report(self, config: FormalCheckConfig) -> str:
        """Generate a formal verification report."""
        lines = []
        lines.append(f"## Formal Verification Report: {config.module_name}")
        lines.append("")
        lines.append(f"**Engine:** {config.engine}")
        lines.append(f"**Depth:** {config.depth}")
        lines.append(f"**Properties:** {len(config.properties)}")
        lines.append(f"  - Asserts: {sum(1 for p in config.properties if p.kind == 'assert')}")
        lines.append(f"  - Assumes: {sum(1 for p in config.properties if p.kind == 'assume')}")
        lines.append(f"  - Covers: {sum(1 for p in config.properties if p.kind == 'cover')}")
        lines.append("")
        lines.append("### Properties")
        lines.append("")
        lines.append("| # | Name | Kind | Category | Expression |")
        lines.append("|---|------|------|----------|------------|")
        for i, p in enumerate(config.properties):
            expr_short = p.expression[:60] + "..." if len(p.expression) > 60 else p.expression
            lines.append(f"| {i+1} | {p.name} | {p.kind} | {p.category} | `{expr_short}` |")
        lines.append("")
        lines.append("### Files")
        lines.append(f"- **SVA:** `formal_{config.module_name}.sv` (bind module)")
        lines.append(f"- **Config:** `{config.module_name}.sby` (SymbiYosys)")
        lines.append("")
        lines.append("### How to Run")
        lines.append("```bash")
        lines.append(f"sby -f {config.module_name}.sby")
        lines.append("```")
        return "\n".join(lines)


def main():
    import argparse
    parser = argparse.ArgumentParser(description="Formal Property Check Generator")
    parser.add_argument("rtl", help="RTL file to analyze")
    parser.add_argument("--depth", type=int, default=20, help="Formal depth")
    parser.add_argument("--engine", default="smtbmc", help="Formal engine")
    parser.add_argument("--output-sva", help="Output SVA file", default="")
    parser.add_argument("--output-sby", help="Output .sby file", default="")
    parser.add_argument("--output-report", help="Output report file", default="")

    args = parser.parse_args()

    if not os.path.exists(args.rtl):
        print(f"[X] RTL file not found: {args.rtl}")
        sys.exit(1)

    checker = FormalChecker(rtl_path=args.rtl)
    config = checker.generate_config(depth=args.depth, engine=args.engine)

    print(checker.generate_report(config))

    if args.output_sva:
        sva = checker.generate_sva(config)
        with open(args.output_sva, "w") as f:
            f.write(sva)
        print(f"[OK] SVA written to {args.output_sva}")

    if args.output_sby:
        sby = checker.generate_sby(config)
        with open(args.output_sby, "w") as f:
            f.write(sby)
        print(f"[OK] .sby written to {args.output_sby}")

    if args.output_report:
        report = checker.generate_report(config)
        with open(args.output_report, "w") as f:
            f.write(report)
        print(f"[OK] Report written to {args.output_report}")


if __name__ == "__main__":
    main()
