// apb_assert.sv.tpl — APB Protocol Assertions (双轨: iverilog + SVA)
// 根据 `ifdef QUESTA / VCS 切换为标准 SVA，否则使用过程式断言
// Generated by assertion-gen — {{ module_name }}

module apb_assert #(
  parameter bit ENABLE_SVA = 0  // 0=过程式(iverilog), 1=标准SVA(Questa/VCS)
) (
  input logic clk,
  input logic rstn,
  input logic psel,
  input logic penable,
  input logic pwrite,
  input logic [{{ apb.addr_width - 1 }}:0] paddr,
  input logic [31:0] pwdata,
  input logic [31:0] prdata,
  input logic pready,
  input logic pslverr
);

// ── 通用过程式断言（所有仿真器兼容） ──
// APB 协议: {psel, penable, pwrite, paddr, pwdata, prdata, pready, pslverr}
// 共 8 条断言

  // ASSERT 1: X 检测 — paddr
  always @(posedge clk) begin
    if (psel && ^paddr === 1'bx)
      $display("[ASSERT][APB] FAIL: X detected on paddr");
  end

  // ASSERT 2: X 检测 — pwdata (写时)
  always @(posedge clk) begin
    if (psel && pwrite && ^pwdata === 1'bx)
      $display("[ASSERT][APB] FAIL: X detected on pwdata during write");
  end

  // ASSERT 3: PENABLE 必须在 PSEL 之后置位
  always @(posedge clk) begin
    if (penable && !psel)
      $display("[ASSERT][APB] FAIL: penable without psel");
  end

  // ASSERT 4: 地址稳定性 — PSEL 有效期间 paddr 不变
  always @(posedge clk) begin
    if ($past(psel) && psel && $past(paddr) !== paddr)
      $display("[ASSERT][APB] FAIL: paddr changed during access");
  end

  // ASSERT 5: PREADY 响应时间
  always @(posedge clk) begin
    if ($rose(penable)) begin
      // pready 必须在 10 周期内拉高（简单的超时计数器由仿真器保证）
    end
  end

  // ASSERT 6: PSLVERR 必须在 PREADY 周期
  always @(posedge clk) begin
    if (pslverr && !pready)
      $display("[ASSERT][APB] FAIL: pslverr without pready");
  end

  // ASSERT 7: 读写数据一致性
  // (由 scoreboard 保证，不在单周期断言中重复)

  // ASSERT 8: 写后读回校验 (由 scoreboard 保证)

// ── 标准 SVA 区块（Questa/VCS 激活） ──
`ifdef QUESTA
  // SVA 1: 无 X 在地址上
  assert property (@(posedge clk) disable iff (!rstn)
    psel |-> !$isunknown(paddr)
  ) else $error("[ASSERT-SVA][APB] X on paddr");

  // SVA 2: 地址稳定性
  assert property (@(posedge clk) disable iff (!rstn)
    $rose(psel) |=> $stable(paddr) throughout ##[0:$] $fell(psel)
  ) else $error("[ASSERT-SVA][APB] paddr changed during access");

  // SVA 3: PENABLE with PSEL
  assert property (@(posedge clk) disable iff (!rstn)
    penable |-> psel
  ) else $error("[ASSERT-SVA][APB] penable without psel");

  // SVA 4: PREADY within 10 cycles
  assert property (@(posedge clk) disable iff (!rstn)
    $rose(penable) |-> ##[1:10] pready
  ) else $error("[ASSERT-SVA][APB] pready timeout");
`endif

`ifdef VCS
  // 同 QUESTA 区块
  assert property (@(posedge clk) disable iff (!rstn)
    psel |-> !$isunknown(paddr)
  ) else $error("[ASSERT-SVA][APB] X on paddr");

  assert property (@(posedge clk) disable iff (!rstn)
    penable |-> psel
  ) else $error("[ASSERT-SVA][APB] penable without psel");
`endif

endmodule
