#!/usr/bin/env python3

"""questa_vcs_support.py — part of digital-verify-pro."""
"""
questa_vcs_support.py — Questa/ModelSim & VCS simulation support.
Generates compile scripts and Makefile targets for professional simulators.
"""
import os, sys, shutil

BASE_DIR = os.path.dirname(__file__)
PROJECT_DIR = os.path.dirname(BASE_DIR)

# ── detect_questa ──
def detect_questa():
    """Detect Questa/ModelSim installation."""
    vsim = shutil.which("vsim")
    vlog = shutil.which("vlog")
    if vsim and vlog:
        return ("questa", vsim, vlog)
    return None

# ── detect_vcs ──
def detect_vcs():
    """Detect VCS installation."""
    vcs = shutil.which("vcs")
    if vcs:
        return ("vcs", vcs, vcs)
    # ---
    return None

# ── gen_questa_do ──
def gen_questa_do(out_dir, module_name, uvm_dir=None):
    """Generate a .do script for Questa/ModelSim.
    Usage: vsim -do compile.do
    """
    rtl_dir = os.path.join(out_dir, "rtl", "rtl")
    env_dir = os.path.join(out_dir, "rtl", "verification", "env")

    do_lines = [
        "# Questa/ModelSim compile script -- auto-generated",
        f"# Module: {module_name}",
        f"# Generated: digital-verify-pro",
        "",
        "# Remove work library",
        "if {[file exists work]} { vdel -all }",
        "vlib work",
        "",
    ]

    # UVM library (if available)
    uvm_arg = "+UVM"
    if uvm_dir:
        # Check if UVM is built into questa or needs explicit path
        uvm_src = os.path.join(uvm_dir, "uvm_pkg.sv")
        # ---
        if os.path.exists(uvm_src):
            uvm_arg = f"-uvmhome {uvm_dir}"

    # Compile RTL sources
    do_lines.append(f"# Compile RTL sources")
    rtl_files = []
    if os.path.exists(rtl_dir):
        for f in sorted(os.listdir(rtl_dir)):
            if f.endswith(".sv"):
                rtl_files.append(os.path.join(rtl_dir, f))
                do_lines.append(f"vlog -sv {uvm_arg} {os.path.join(rtl_dir, f)}")

    # Compile UVM env sources in order
    if os.path.exists(env_dir):
        do_lines.append(f"")
        do_lines.append(f"# Compile verification environment")
        # Walk env dir in dependency order
        order = ["", "interfaces", "agents", "bfm", "ral", "scoreboard",
                 "coverage", "assertions", "sequences", "tests"]
        for sub in order:
            src_dir = os.path.join(env_dir, sub) if sub else env_dir
            if os.path.exists(src_dir):
                for f in sorted(os.listdir(src_dir)):
                    if f.endswith(".sv"):
                        do_lines.append(f"vlog -sv {uvm_arg} {os.path.join(src_dir, f)}")
# ---

    do_lines.append("")
    do_lines.append(f"# Compile tb_top")
    tb_top = os.path.join(env_dir, "tb_top.sv")
    if os.path.exists(tb_top):
        do_lines.append(f"vlog -sv {uvm_arg} {tb_top}")

    do_lines.append("")
    do_lines.append(f"# Load and run simulation")
    do_lines.append(f"vsim -c work.tb_top {uvm_arg}")
    do_lines.append("run -all")
    do_lines.append("quit")

    do_path = os.path.join(out_dir, "sim_work", f"questa_compile.do")
    with open(do_path, "w") as f:
        f.write("\n".join(do_lines))

    # Also generate a Makefile for parallel compilation
    mk_path = os.path.join(out_dir, "sim_work", "Makefile.questa")
    mk_lines = [
        f"# Makefile for Questa/ModelSim -- {module_name}",
        "all: compile simulate",
        "",
        "compile:",
        f"\tvlog -sv +UVM $(shell find {rtl_dir.replace(chr(92),'/')}/ -name '*.sv' 2>/dev/null)",
        # ---
        f"\tvlog -sv +UVM $(shell find {env_dir.replace(chr(92),'/')}/ -name '*.sv' 2>/dev/null)",
        "",
        "simulate: compile",
        "\tvsim -c work.tb_top +UVM -do 'run -all; quit'",
        "",
        "clean:",
        "\tvdel -all",
        "\trm -rf work",
    ]
    with open(mk_path, "w") as f:
        f.write("\n".join(mk_lines))

    print(f"  [GEN] Questa do script: {do_path}")
    print(f"  [GEN] Questa Makefile:  {mk_path}")
    print(f"  [USE] vsim -do {do_path}")

    return do_path

# ── gen_vcs_script ──
def gen_vcs_script(out_dir, module_name, uvm_dir=None):
    """Generate a compile/simulate script for VCS."""
    rtl_dir = os.path.join(out_dir, "rtl", "rtl")
    env_dir = os.path.join(out_dir, "rtl", "verification", "env")

    sh_lines = [
        "#!/bin/bash",
        # ---
        f"# VCS compile script -- {module_name}",
        "# Generated by digital-verify-pro",
        "",
        "set -e",
        f"SCRIPT_DIR=\"$(cd \"$(dirname \"$0\")\" && pwd)\"",
        f"OUT_DIR=\"$SCRIPT_DIR/..\"",
        "",
    ]

    # Find all sources
    rtl_files = []
    if os.path.exists(rtl_dir):
        for f in sorted(os.listdir(rtl_dir)):
            if f.endswith(".sv"):
                rtl_files.append(os.path.join(rtl_dir, f))

    env_files = []
    if os.path.exists(env_dir):
        for root, _, files in os.walk(env_dir):
            for f in sorted(files):
                if f.endswith(".sv"):
                    env_files.append(os.path.join(root, f))

    all_files = rtl_files + env_files
    file_list = " \\\n    ".join(all_files)
    # ---
    uvm_flag = "+UVM" if uvm_dir else ""

    sh_lines.extend([
        f"echo \"Compiling {len(all_files)} source files...\"",
        "",
        f"vcs -sverilog -full64 -debug_all {uvm_flag} \\",
        f"    -o simv_{module_name} \\",
        f"    {file_list}",
        "",
        f"echo \"Running simulation...\"",
        f"./simv_{module_name} +UVM_TESTNAME=base_test | tee sim.log",
        "",
        "echo \"Done. Check sim.log for results.\"",
    ])

    sh_path = os.path.join(out_dir, "sim_work", "vcs_compile.sh")
    with open(sh_path, "w") as f:
        f.write("\n".join(sh_lines))
    os.chmod(sh_path, 0o755)

    # Also Makefile
    mk_path = os.path.join(out_dir, "sim_work", "Makefile.vcs")
    mk_lines = [
        f"# VCS Makefile -- {module_name}",
        f"RTL_DIR   = {rtl_dir}",
        # ---
        f"ENV_DIR   = {env_dir}",
        "SRCS     = $(shell find $(RTL_DIR) -name '*.sv') $(shell find $(ENV_DIR) -name '*.sv')",
        "",
        "all: compile simulate",
        "",
        "compile:",
        f"\tvcs -sverilog -full64 +UVM -o simv_{module_name} $(SRCS)",
        "",
        "simulate: compile",
        f"\t./simv_{module_name} +UVM_TESTNAME=base_test 2>&1 | tee sim.log",
        "",
        "clean:",
        f"\trm -rf simv_{module_name}* csrc* *.log",
    ]
    with open(mk_path, "w") as f:
        f.write("\n".join(mk_lines))

    print(f"  [GEN] VCS script: {sh_path}")
    print(f"  [GEN] VCS Makefile: {mk_path}")
    print(f"  [USE] cd sim_work && bash vcs_compile.sh")

    return sh_path

# ── main ──
def main():
    import argparse
    # ---
    ap = argparse.ArgumentParser(description="Generate EDA tool support files")
    ap.add_argument("--spec", "-s", default="")
    ap.add_argument("--outdir", "-o", default="")
    ap.add_argument("--questa", action="store_true", help="Generate Questa scripts")
    ap.add_argument("--vcs", action="store_true", help="Generate VCS scripts")
    ap.add_argument("--detect", action="store_true", help="Detect available simulators")
    args = ap.parse_args()

    if args.detect:
        q = detect_questa()
        v = detect_vcs()
        print("Detected simulators:")
        print(f"  Questa/ModelSim: {'YES' if q else 'NO'}")
        print(f"  VCS:            {'YES' if v else 'NO'}")
        return

    # Resolve spec/outdir
    spec = args.spec
    if not spec:
        for c in ["i2c_spec.yml", "pcie_ep_spec.yml", "arm_pl061_gpio.yml"]:
            f = os.path.join(PROJECT_DIR, c)
            if os.path.exists(f):
                spec = f; break
    if not spec or not os.path.exists(spec):
        print("[X] Spec not found"); sys.exit(1)
# ---

    out_dir = os.path.abspath(args.outdir) if args.outdir else os.path.join(PROJECT_DIR, "output")
    # Check condition
    if not os.path.exists(os.path.join(out_dir, "rtl", "verification", "env")):
        print(f"[X] {out_dir} has no env. Run pipeline first."); sys.exit(1)

    # Get module name
    from template_engine import build_spec_data, extract_module_name
    module_name = extract_module_name(out_dir)
    if module_name == "unknown":
        module_name = build_spec_data(spec).get("module_name", "unknown")

    uvm_dir = os.path.join(PROJECT_DIR, "uvm")
    # Check condition
    if not os.path.exists(os.path.join(uvm_dir, "uvm_pkg.sv")):
        uvm_dir = None

    print(f"{'='*60}")
    print(f"  Generating EDA scripts for {module_name}")
    print(f"{'='*60}")

    if args.questa:
        gen_questa_do(out_dir, module_name, uvm_dir)
    if args.vcs:
        gen_vcs_script(out_dir, module_name, uvm_dir)
    if not args.questa and not args.vcs:
        gen_questa_do(out_dir, module_name, uvm_dir)
        # ---
        gen_vcs_script(out_dir, module_name, uvm_dir)

    print(f"{'='*60}")
    print(f"  Done. Scripts in {out_dir}/sim_work/")
    print(f"{'='*60}")

if __name__ == "__main__":
    main()
